### ISSUE TITLE
posenetSocket.exe: Cannot find module 'default/dist/socket.js'

### ISSUE THREAD

**Issue by simserg** [oveddan/posenet-for-installations#15]
I get this error when I run posenetSocket.exe:
```
module.js:491
    throw err;
    ^

Error: Cannot find module 'default/dist/socket.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
```
Indeed there is no "socket.js" in posenet-for-installations-master/server/dist/
Though everything works great when I do "yarn start-server"

**Comment by zugende** [comment]
get the same error
@simserg did you solve the problem my putting socket.js back into the folder?

**Comment by simserg** [comment]
#zugende I couldn't solve the problem. 
There was another socket.js file in the project so I tried copying it into /server/dist, but I got the same error. I also copied the socket.js file into a new directory at /server/default/dist/, but still got the error. I also tried moving /default/dist/socket.js around in the /server/directory/, but alas the error remains.
I don't really know where it is trying to look for socket.js.

**Comment by hulsmeier** [comment]
Was anyone able to figure out this issue?

**Comment by PrecociouslyDigital** [comment]
The error stems from `client/distribute.js` having an incorrect entrypoint; I've submitted a pull request here: #29
