### ISSUE TITLE
yarn download-models fails

### ISSUE THREAD

**Issue by b005t3r** [oveddan/posenet-for-installations#16]
```
> node downloadModels.js

downloading file at https://storage.googleapis.com/tfjs-models/weights/posenet/mobilenet_v1_101/manifest.json
downloading file at https://storage.googleapis.com/tfjs-models/weights/posenet/mobilenet_v1_100/manifest.json
downloading file at https://storage.googleapis.com/tfjs-models/weights/posenet/mobilenet_v1_075/manifest.json
downloading file at https://storage.googleapis.com/tfjs-models/weights/posenet/mobilenet_v1_050/manifest.json
(node:53899) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at loadAndSaveManifest (/Users/booster/Documents/JS/posenet-for-installations/client/downloadModels.js:48:25)
    at async downloadCheckpoint (/Users/booster/Documents/JS/posenet-for-installations/client/downloadModels.js:79:20)
    at async downloadCheckpointFromSubfolder (/Users/booster/Documents/JS/posenet-for-installations/client/downloadModels.js:93:3)
    at async Promise.all (index 3)

```

**Comment by oveddan** [comment]
I can confirm this issue.  Stand by for the posenet 2.0 upgrade.

**Comment by oveddan** [comment]
Has to do with the model files now being gzipped:
https://github.com/tensorflow/tfjs/issues/1712

**Comment by b005t3r** [comment]
Thanks, but is there a solution? :)

**Comment by oveddan** [comment]
@b005t3r this is now fixed.

**Comment by b005t3r** [comment]
Thanks! I managed to download all 4 models, however it didn't work the first time I tried it for some reason.

I see the models are actually in some strange format - any idea how can I convert those to pb format, that I can use with TF for Java?

**Comment by oveddan** [comment]
These are the legacy format of tf.js, and posenet 2.0 using a frozen graph format.  That being said, check out https://github.com/rwightman/posenet-python in which these weights are downloaded and converted into a python model.
